# Generated by Django 6.0.1 on 2026-02-23 13:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_member', models.BooleanField(default=False)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=40, unique=True)),
                ('service_type', models.CharField(choices=[('Baptism', 'Baptism'), ('Dedication', 'Dedication'), ('Wedding', 'Wedding')], max_length=20)),
                ('object_id', models.UUIDField()),
                ('issued_date', models.DateField(default=django.utils.timezone.localdate)),
                ('design_template', models.CharField(max_length=60)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/')),
                ('is_valid', models.BooleanField(default=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_account', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_account', to='base.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('officiant', models.CharField(blank=True, max_length=120)),
                ('admin_comment', models.TextField(blank=True)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baptism', to='base.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BabyDedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('dedication_date', models.DateField(blank=True, null=True)),
                ('officiant', models.CharField(blank=True, max_length=120)),
                ('admin_comment', models.TextField(blank=True)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_dedications', to='base.person')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='father_dedications', to='base.person')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mother_dedications', to='base.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding_date', models.DateField()),
                ('officiant', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('admin_comment', models.TextField(blank=True)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bride_weddings', to='base.person')),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groom_weddings', to='base.person')),
            ],
            options={
                'ordering': ['-wedding_date'],
            },
        ),
    ]
