# Generated by Django 6.0.2 on 2026-02-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='member_profiles/'),
        ),
    ]
