# Generated by Django 6.0.2 on 2026-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_memberaccount_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='babydedication',
            name='scripture_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='babydedication',
            name='scripture_text',
            field=models.TextField(blank=True),
        ),
    ]
