# Generated by Django 6.0.2 on 2026-04-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_babydedication_status_alter_baptism_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babydedication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Married', 'Married')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='baptism',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Married', 'Married')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Married', 'Married')], default='Scheduled', max_length=20),
        ),
    ]
