# Generated by Django 6.0.2 on 2026-06-19 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_babydedication_status_alter_baptism_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('activity_type', models.CharField(choices=[('All', 'All'), ('Baptism', 'Baptism'), ('Dedication', 'Dedication'), ('Wedding', 'Wedding')], default='All', max_length=20)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'activity_type')},
            },
        ),
    ]
