# Generated by Django 6.0.2 on 2026-06-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_blackoutdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='couple_photo',
            field=models.ImageField(blank=True, upload_to='wedding_photos/', verbose_name='Couple Photo'),
        ),
    ]
