# Generated by Django 6.0.2 on 2026-06-27 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_wedding_couple_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingCeremony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groom_church_name', models.CharField(blank=True, max_length=200)),
                ('bride_church_name', models.CharField(blank=True, max_length=200)),
                ('wedding_date', models.DateField()),
                ('officiant', models.CharField(blank=True, max_length=120)),
                ('witnesses', models.JSONField(blank=True, default=list)),
                ('marriage_resolution', models.CharField(blank=True, choices=[('Divorced', 'Divorced'), ('Annulled', 'Annulled')], max_length=20)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('available_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceremonies', to='base.availableslot')),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bride_ceremonies', to='base.person')),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groom_ceremonies', to='base.person')),
                ('officiant_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.officiant')),
            ],
            options={
                'ordering': ['-wedding_date'],
            },
        ),
        migrations.AddField(
            model_name='wedding',
            name='ceremony_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_wedding', to='base.weddingceremony'),
        ),
        migrations.CreateModel(
            name='WeddingCertificateExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple_photo_used', models.ImageField(blank=True, upload_to='wedding_cert_photos/')),
                ('witness_names_display', models.TextField(blank=True)),
                ('gospel_reading', models.CharField(blank=True, max_length=200)),
                ('officiant_title', models.CharField(blank=True, max_length=120)),
                ('ceremony', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_extra', to='base.weddingceremony')),
            ],
            options={
                'verbose_name': 'Wedding Certificate Extra',
                'verbose_name_plural': 'Wedding Certificate Extras',
            },
        ),
        migrations.CreateModel(
            name='WeddingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_consented', models.BooleanField(default=False)),
                ('partner_consented_at', models.DateTimeField(blank=True, null=True)),
                ('partner_invite_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('partner_is_member', models.BooleanField(default=False)),
                ('partner_non_member_data', models.JSONField(blank=True, default=dict)),
                ('partner_gender_expected', models.CharField(blank=True, max_length=10)),
                ('couple_photo', models.ImageField(blank=True, upload_to='wedding_photos/', verbose_name='Couple Photo')),
                ('submitter_role', models.CharField(choices=[('groom', 'Groom'), ('bride', 'Bride')], max_length=10)),
                ('submitter_health_document', models.FileField(blank=True, upload_to='wedding_health_documents/')),
                ('partner_health_document', models.FileField(blank=True, upload_to='wedding_health_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Married', 'Married')], default='Pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_wedding_requests', to='base.person')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_wedding_requests', to='base.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='weddingceremony',
            name='wedding_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ceremony', to='base.weddingrequest'),
        ),
    ]
