# Generated by Django 6.0.2 on 2026-06-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_weddingceremony_wedding_ceremony_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingceremony',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
