# Generated by Django 6.0.2 on 2026-06-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_wedding_resolution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='visitor_notes',
            field=models.TextField(blank=True),
        ),
    ]
