# Generated by Django 6.0.2 on 2026-07-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_visitor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingrequest',
            name='available_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_requests', to='base.availableslot'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='officiant',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
